### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by EzJaja** [Dragon-0609/Yuki-Theme#37]
**Describe the bug**
IDE просто на отображается
Использовал плагин, программой так и не понял как пользоваться

**To Reproduce**
Шаги получения бага:
1. Делаем все как в видео
2. Запускаем IDE
3. IDE появляется на секунду с белой темой, затем просто пропадает, хотя процесс висит, и в панели задач видно IDE, но "открыть" не получается

**Expected behavior**
Возможно проблема в том что поддерживается только на 10 винде
или может быть изза моей дно видюхи

**Screenshots**
Скриншот думаю бессмысленный так-как смотреть буквально не на что .-.

**Desktop (please complete the following information):**
 - Винда 7x64 SP1
 - 
**Additional context**
Пофикси плиз, идея просто топовая,
я искал темную тему, а нашел "золото".. правда не рабочее..

**Comment by Dragon-0609** [comment]
> Возможно проблема в том что поддерживается только на 10 винде

Возможно. Я проверял только в 10-ой. Посмотрю, как в моей windows 7 будет вести себя плагин.

> IDE появляется на секунду с белой темой, затем просто пропадает, хотя процесс висит, и в панели задач видно IDE, но "открыть" не получается

Скажите версию IDE. Я проверял только в 3.8.2. Возможно в других версиях какие-то части не существуют и поэтому интеграция ломает IDE.

> программой так и не понял как пользоваться

[Тут написано](https://dragon-0609.github.io/Yuki-Theme/guide/installation#program-installation)

> или может быть изза моей дно видюхи

Кстати, для плагина нужно .NET Framework 4.8. Проверьте версию NET Framework. Возможно проблема в этом.

> Пофикси плиз, идея просто топовая

Обязательно 👍

**Comment by Dragon-0609** [comment]
> может быть изза моей дно видюхи

Нет. Я проверил на своем windows 7 x64 SP1. Всё работает как надо. Возможно проблема в версии .NET Framework или в версии PascalABC.NET. 
Версия .NET Framework должна быть 4.8. А версия PascalABC.NET 3.8.2.

**Comment by EzJaja** [comment]
IDE версия 3.8.3 сборка 3104 15.04.2022
версию Net Framework не знаю, но я токо скачал паскаль abc и сразу скачал твой плагин, наверно новая, если оно так работает.

**Comment by Dragon-0609** [comment]
> версию Net Framework не знаю

[Тут описано как узнать](https://support.citrix.com/article/CTX224771)

**Comment by EzJaja** [comment]
фреймворк версии 4.8

**Comment by Dragon-0609** [comment]
Только что проверил в IDE версия 3.8.3 сборка 3104 15.04.2022. В Windows 7 и 10 проблем не возникло.

Сейчас я напишу дебаг версию, чтобы вы могли отправить мне логи.

**Comment by Dragon-0609** [comment]
В панеле задач иконки не видно?

**Comment by EzJaja** [comment]
ааа упс, мой недочет..

**Comment by EzJaja** [comment]
Кстати, при установке, в архиве папка Themes пуста, конечно понимаю, может они туда добавляются из библиотеки, но как вариант может быть

**Comment by EzJaja** [comment]
Открыл, вылетела ошибка записи, отказано в доступе

**Comment by Dragon-0609** [comment]
папка Themes для пользовательских тем. Все темы по умолчанию встроенные во внутрь dll.  Например, темы _The Doki Theme_ (большинство тем) находятся внутри _Yuki Theme.Themes.dll_.

**Comment by Dragon-0609** [comment]
> Открыл, вылетела ошибка записи, отказано в доступе

Может быть файл не-до закрылся? Сейчас допилю нормальное закрытие файла.

**Comment by EzJaja** [comment]
Открыл с правами админа всё запустилось, жду 10 сек..

**Comment by EzJaja** [comment]
Вывод:

> 2022.04.19 21:47:46  - LOGGING STARTED...
> 2022.04.19 21:47:47  - Showing logo
> 2022.04.19 21:47:47  - Logo showed
> 2022.04.19 21:47:47  - Loading colors
> 2022.04.19 21:47:47  - Loading image
> 2022.04.19 21:47:47  - Inspecting brackets
> 2022.04.19 21:47:47  - Updating colors
> 2022.04.19 21:47:47  - Updating colors end
> 2022.04.19 21:47:47  - Loading svg
> 2022.04.19 21:47:48  - Initializing sticker
> 2022.04.19 21:47:48  - Adding to settings
> 2022.04.19 21:47:49  - Main window properties:
> 						Disposed: False, Visibility: True
> 2022.04.19 21:47:49  - Hiding logo
> 2022.04.19 21:47:49  - Logo hidden
> 2022.04.19 21:47:49  - Initializing styles
> 2022.04.19 21:47:50  - Styles initialized
> 2022.04.19 21:47:50  - Searching Yuki Theme menu item
> 2022.04.19 21:47:50  - Yuki Theme menu item found
> Произошла ошибка при отправке запроса.
>    в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    в Yuki_Theme.Core.Forms.DownloadForm.<CheckUpdate>d__7.MoveNext()
> 2022.04.19 21:49:59  - LOGGING END.

**Comment by EzJaja** [comment]
я ничего не понимаю в программировании на С# но, могли ли вы сделать конструкцию по типу питоновского try except чтобы при ошибке могло сразу выдать, что случилось с программой?

**Comment by EzJaja** [comment]
Сделал, сейчас проверю... это никак не скажется на основной работе аддона?

**Comment by Dragon-0609** [comment]
> я ничего не понимаю в программировании на С# но, могли ли вы сделать конструкцию по типу питоновского try except чтобы при ошибке могло сразу выдать, что случилось с программой?

Оно должно было выдать хоть какую-ту ошибку, но вместо этого похоже IDE решил промолчать. Из-за того что IDE  собирается в качестве релиза, невозможно узнать в какой именно строке ошибка.

**Comment by Dragon-0609** [comment]
> это никак не скажется на основной работе аддона?

Никак. Это просто авто проверка обновлений плагина. Если хотите проверить обновление, можно нажать на _Update_ внутри настроек плагина.

**Comment by EzJaja** [comment]
к сожалению, ничего не изменилось, опять пропала, зато текст логов уже другой... 

> 2022.04.19 22:04:27  - LOGGING STARTED...
> 2022.04.19 22:04:27  - Showing logo
> 2022.04.19 22:04:27  - Logo showed
> 2022.04.19 22:04:27  - Loading colors
> 2022.04.19 22:04:27  - Loading image
> 2022.04.19 22:04:27  - Inspecting brackets
> 2022.04.19 22:04:27  - Updating colors
> 2022.04.19 22:04:28  - Updating colors end
> 2022.04.19 22:04:28  - Loading svg
> 2022.04.19 22:04:28  - Initializing sticker
> 2022.04.19 22:04:28  - Adding to settings
> 2022.04.19 22:04:30  - Main window properties:
> 						Disposed: False, Visibility: True
> 2022.04.19 22:04:30  - Hiding logo
> 2022.04.19 22:04:30  - Logo hidden
> 2022.04.19 22:04:30  - Initializing styles
> 2022.04.19 22:04:30  - Styles initialized
> 2022.04.19 22:04:30  - Searching Yuki Theme menu item
> 2022.04.19 22:04:30  - Yuki Theme menu item found
> 2022.04.19 22:05:01  - LOGGING END.

**Comment by Dragon-0609** [comment]
Окно IDE всё равно не видно?

Но в логе написано:
```
Main window properties:
Disposed: False, Visibility: True
```

Там написано что главное окно IDE не закрыто и оно сейчас не скрыто.

Как странно 😯

**Comment by EzJaja** [comment]
Может быть мое 1 из первых утверждений было правильным? может быть моя видюха (Видеокарта) или Драйверы под неё устарели или не подходят?

**Comment by EzJaja** [comment]
ахахха нашел 1 абьюз, пока окошко видно около секунды, можно нажать на Сервис и окно с Сервисом не пропало, теперь могу нажать на Настройки и Yuki Theme... щас посмотрю можно ли это использовать..

**Comment by Dragon-0609** [comment]
> может быть моя видюха (Видеокарта) или Драйверы под неё устарели или не подходят?

Не думаю.

**Comment by EzJaja** [comment]
В настройках выключил Показать Стикер, Показать обои, лого при старте и обновление до первой версии... и... так, при запуске все-равно пропала, значит _проблема не из-за графической части_, хоть какой-то результат

**Comment by Dragon-0609** [comment]
Думаю я знаю где проблема.

Попробуйте это:

https://drive.google.com/file/d/1VWHmm_seFvgh_4ceML9fh_wwI4i-Y4cA/view?usp=sharing

**Comment by EzJaja** [comment]
Опять пропало, логи как в предыдущий раз

**Comment by EzJaja** [comment]
а нет, есть небольшое отличие

**Comment by EzJaja** [comment]
> 2022.04.19 22:19:28  - LOGGING STARTED...
> 2022.04.19 22:19:28  - Showing logo
> 2022.04.19 22:19:28  - Logo showed
> 2022.04.19 22:19:28  - Loading colors
> 2022.04.19 22:19:28  - Loading image
> 2022.04.19 22:19:28  - Inspecting brackets
> 2022.04.19 22:19:28  - Updating colors
> 2022.04.19 22:19:29  - Updating colors end
> 2022.04.19 22:19:29  - Loading svg
> 2022.04.19 22:19:29  - Initializing sticker
> 2022.04.19 22:19:29  - Adding to settings
> 2022.04.19 22:19:31  - Main window properties:
> 						Disposed: False, Visibility: True
> 2022.04.19 22:19:31  - Hiding logo
> 2022.04.19 22:19:31  - Logo hidden
> 2022.04.19 22:19:31  - Initializing styles
> 2022.04.19 22:19:31  - Initializing styles terminated
> 2022.04.19 22:19:31  - Searching Yuki Theme menu item
> 2022.04.19 22:19:31  - Yuki Theme menu item found
> 2022.04.19 22:19:31  - LOGGING END.

**Comment by Dragon-0609** [comment]
> а нет, есть небольшое отличие

Вы про:

Initializing styles terminated

Я специально подумал, что из-за стилей. Сейчас отключу почти всё, тогда и посмотрим какая часть вызывает ошибку.

**Comment by Dragon-0609** [comment]
Отключил:

https://drive.google.com/file/d/1VWHmm_seFvgh_4ceML9fh_wwI4i-Y4cA/view?usp=sharing

**Comment by Dragon-0609** [comment]
А какие плагины у вас установлены в Pascal?

Чтобы проверить это, временно переместите _Yuki Theme Plugin.dll_ куда нибудь, после чего откройте Pascal. Вы можете узнать какие плагины установлены нажимая на Помощь -> О программе.  Там будет список. Плагины написаны как _Plugin_ в ячейке _Тип_

**Comment by EzJaja** [comment]
Хорошо сейчас..

**Comment by EzJaja** [comment]
Ооо я с помощью той фичи, успел кликнуть на Yuki Theme, окно открылось, как показала практика - работает всё, кроме самого ide...

**Comment by EzJaja** [comment]
оу там можно темы выбирать, красата

**Comment by Dragon-0609** [comment]
Похоже даже отключение многих частей не помог. Ладно, перейдём к тотальной блокировке функций плагина. Оставлю только самые базовые (фон, стикер). Сейчас отправлю

**Comment by EzJaja** [comment]
Все компоненты
> Core PascalABCCompiler.core
> Parser PascalABC.NET
> Parser DocTags
> Convertor Optimizer
> Plugin Code Templates Plugin
> Plugin InternalError Report Genegator
> Plugin PT4 Provider
> Plugin Yuki Theme
> Assembly ICSharpCode.TextEditor.dll
> Assembly DebuggerCore.dll
> Assembly Weifen.Luo.WinFormsUI.Docking.dll

**Comment by Dragon-0609** [comment]
Отключенный:

https://drive.google.com/file/d/1VWHmm_seFvgh_4ceML9fh_wwI4i-Y4cA/view?usp=sharing

**Comment by EzJaja** [comment]
Ой а там надо было ТОЛЬКО это засунуть???? я просто кидал в папку и нажимал "заменить всё что можно"

**Comment by EzJaja** [comment]
сейчас попробую ТОЛЬКО это засунуть

**Comment by Dragon-0609** [comment]
> надо было ТОЛЬКО это засунуть???

Это просто изменения в самом плагине. Другие части остаются не изменёнными. 

> я просто кидал в папку и нажимал "заменить всё что можно"

Так нужно сделать. Если вы заметили, то в релизах внутри zip много файлов, а в zip который я отправил только один файл. Короче, другие файлы тоже необходимы.

Все компоненты как у меня. Так что это не должно быть проблемой.

Если даже в отключенном IDE будет пропадать, тогда попробуйте использовать старые версии начиная с 2-ой версией:

https://github.com/Dragon-0609/Yuki-Theme/releases

Возможно с обновлением какие-то функции стали нестабильными. Поэтому нужно узнать в какой версии плагин работает, в какой не работает.

**Comment by EzJaja** [comment]
Хорошо

**Comment by Dragon-0609** [comment]
Нужные файлы для работы плагина:

```
ColorSlider.dll
CommonMark.dll
Cyotek.Windows.Forms.ColorPicker.dll
FastColoredTextBox.dll
Fizzler.dll
Microsoft.WindowsAPICodePack.dll
Microsoft.WindowsAPICodePack.ExtendedLinguisticServices.dll
Microsoft.WindowsAPICodePack.Sensors.dll
Newtonsoft.Json.dll
Svg.dll
System.Memory.dll
System.Runtime.CompilerServices.Unsafe.dll
Yuki Theme.Core.dll
Yuki Theme Plugin.dll
Yuki Theme.Themes.dll
```

**Comment by EzJaja** [comment]
тут первая это версия V3.0b2 короче полагаю, её и нужно

**Comment by Dragon-0609** [comment]
Есть 2-ая страница. Там 2-я версия.

https://github.com/Dragon-0609/Yuki-Theme/releases?page=2

**Comment by EzJaja** [comment]
> Нужные файлы для работы плагина:
> 
> ```
> ColorSlider.dll
> CommonMark.dll
> Cyotek.Windows.Forms.ColorPicker.dll
> FastColoredTextBox.dll
> Fizzler.dll
> Microsoft.WindowsAPICodePack.dll
> Microsoft.WindowsAPICodePack.ExtendedLinguisticServices.dll
> Microsoft.WindowsAPICodePack.Sensors.dll
> Newtonsoft.Json.dll
> Svg.dll
> System.Memory.dll
> System.Runtime.CompilerServices.Unsafe.dll
> Yuki Theme.Core.dll
> Yuki Theme Plugin.dll
> Yuki Theme.Themes.dll
> ```

опаа нету одного файла.. 
Microsoft.WindowsAPICodePack.ExtendedLinguisticServices.dll

**Comment by EzJaja** [comment]
это еще в седьмой версии..

**Comment by Dragon-0609** [comment]
> опаа нету одного файла.. Microsoft.WindowsAPICodePack.ExtendedLinguisticServices.dll

Насколько я знаю это во всех версиях не хватает того файла. Ну, не думаю что из-за него. Он нужен только для выбора папки.

**Comment by Dragon-0609** [comment]
Начиная с 8-ой версии такой не хваткой файлов не будет. Как бы там не было это не причина странного поведения плагина.

**Comment by Dragon-0609** [comment]
Вот те файлы:

https://drive.google.com/file/d/1muZcHhVKn_L8rf6mIQfg8HIXGmfjxAS3/view?usp=sharing

**Comment by EzJaja** [comment]
возник вопрос, поскольку версия 2.0 старая, может возникнуть такая проблема, чтоб какие-нибудь новые файлы остались, и могли бы помешать запуску уже старой версии?

**Comment by EzJaja** [comment]
2.0 не работает.

**Comment by EzJaja** [comment]
> Вот те файлы:
> 
> https://drive.google.com/file/d/1muZcHhVKn_L8rf6mIQfg8HIXGmfjxAS3/view?usp=sharing

"Те"? это которые? я на данный момент попробовал 2.0, уже с ней не работает

**Comment by Dragon-0609** [comment]
> может возникнуть такая проблема, чтоб какие-нибудь новые файлы остались, и могли бы помешать запуску уже старой версии?

Не помешает, если вы перезаписывали при распаковке старой версии.

**Comment by EzJaja** [comment]
не понятно, если перезаписывали файлы (тоесть нажать Заменить всё) то так и делал, если перезапись имеется в виду полная замена всех файлов плагина, то это сложно, так-как отсутствует деинсталлятор

**Comment by Dragon-0609** [comment]
> 2.0 не работает.

😐. Как это не работает? Не отображается Pascal?

2-ая версия довольно старая. Если она не работает, то мало верится в то что другие будут работать. 🤔 Хотя, можно проверить версии.

**Comment by Dragon-0609** [comment]
> если перезапись имеется в виду полная замена всех файлов плагина

Да.

**Comment by EzJaja** [comment]
> . Как это не работает? Не отображается Pascal?

К сожалению, да, та-же проблема.. Если версии и паскаля и фреймворка те-же, может что нибудь еще нужно обновить?

**Comment by EzJaja** [comment]
> > если перезапись имеется в виду полная замена всех файлов плагина
> 
> Да.

Тогда деинсталлятор нужен для полного удаления, все-таки удалить просто файлы иногда бывает не достаточно

**Comment by EzJaja** [comment]
> > если перезапись имеется в виду полная замена всех файлов плагина
> 
> Да. Можно просто распаковать все файлы. Старая версия просто не будет реагировать на файлы новой версии.

А ой не прочитал это

**Comment by Dragon-0609** [comment]
Если не работает, тогда вам придется пока что довольствоваться программой. 

А мне нужно найти способ как-нибудь повторить то что случается в вашем случае. Ибо если не знать в чём проблема, найти решение очень трудно.

[Тут гайд](https://dragon-0609.github.io/Yuki-Theme/guide/installation#program-installation) как использовать программу.

В программе можно применить тему, но будет изменено только сам редактор.

**Comment by EzJaja** [comment]
Хорошо, я пока попробую найти в интернете на счет этого

**Comment by Dragon-0609** [comment]
При нажатии `Alt + Tab` появляется окно IDE? Если так, тогда попробуйте в него зайти.

**Comment by EzJaja** [comment]
уже проверял ранее, тоже самое, не работает

**Comment by EzJaja** [comment]
Пробую полностью переустановить .net framework, также найду все обновления для его стабильной работы в интернете

**Comment by EzJaja** [comment]
ООООО ХОТЬ ЧТОТО, после переустановки .net, при полной переустановке плагина на новую версию, попытался открыть паскаль ии... вышла ошибка! оу да, по сравнению с "пустым игнором" это очень полезно, скрин:
![image](https://user-images.githubusercontent.com/103786737/164313050-b62bfec9-7fd6-4c12-8f43-df461a165bb9.png)

**Comment by EzJaja** [comment]
Мда я забыл нажать Details, минутку...

**Comment by EzJaja** [comment]
оу текст невероятно большой, для экономии места помещу в привнот https://privnote.com/5NU8w8pu#YlDKt7me6

**Comment by Dragon-0609** [comment]
вышла ошибка:

```
System.ArgumentNullException: Value cannot be null.
Parameter name: brush
   at System.Drawing.Graphics.FillPath(Brush brush, GraphicsPath path)
   at Yuki_Theme_Plugin.Controls.DockStyles.YukiDockPaneStrip.DrawTab_Document(Graphics g, Tab tab, Rectangle rect)
   at ...
```

Я знаю в чём ошибка. Дело в том что вы отключили `лого при старте`, и из-за этого пока цвета не загружены, стили применяются, которым нужны цвета.

Я проверил у себя с отключенным `лого при старте`, но такого не произошло. Возможно мой пк немного притормаживает при применении стилей. А пока применяются стили, цвета успевают загрузиться, насколько я понимаю.

Как бы там не было, спасибо за отчет об ошибке. К бета версии будет исправлено.

**Comment by Dragon-0609** [comment]
А чтобы включить `лого при старте`:

Для этого `Win + R`, выйдет окошко. Напишите: `regedit` . Нажмите ОК. После чего доберитесь до: `HKEY_CURRENT_USER\Software\YukiTheme` . Там будет цифры и значения.

Если есть цифра 11, нажмите на неё 2 раза, после чего выйдет окошко. Там напишите True.

**Comment by EzJaja** [comment]
Извиняюсь за некропост, только сейчас заметил что вы написали.... с лого при старте тоже не работает.

**Comment by Dragon-0609** [comment]
Кстати, вы можете дать список плагинов?

Для этого временно переместите Yuki Theme Plugin.dll куда нибудь (если он у вас есть), после чего откройте Pascal. Вы можете узнать какие плагины установлены нажимая на Помощь -> О программе. Там будет список. 

А ещё попробуйте открыть Pascal с правами админа

**Comment by EzJaja** [comment]
> Все компоненты
> 
> > Core PascalABCCompiler.core
> > Parser PascalABC.NET
> > Parser DocTags
> > Convertor Optimizer
> > Plugin Code Templates Plugin
> > Plugin InternalError Report Genegator
> > Plugin PT4 Provider
> > Plugin Yuki Theme
> > Assembly ICSharpCode.TextEditor.dll
> > Assembly DebuggerCore.dll
> > Assembly Weifen.Luo.WinFormsUI.Docking.dll

я уже слал компоненты (плагины в том числе), не думаю что что-то изменилось, тк сам я ничего не трогал, права админа не помогли

**Comment by Dragon-0609** [comment]
Я хочу проверить из-за чего именно окно скрывается. Поэтому я собрал тестовый плагин, который меняет скроллбар IDE:

![screen](https://user-images.githubusercontent.com/80271099/189487968-1c39d5fc-8256-4c7b-95a3-17df0e968db1.png)

Поэтому, временно переместите `Yuki Theme Plugin.dll` и распакуйте zip в папку с Pascal. После чего скажите мне, показывается окно или нет.

[TestPlugin.zip](https://github.com/Dragon-0609/Yuki-Theme/files/9540571/TestPlugin.zip)
